services:
  oracledb:
    image: gvenzl/oracle-free:latest
    container_name: custom_orm_oracle
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=oracle_pass_123
      - APP_USER=orm_user
      - APP_USER_PASSWORD=orm_pass_123
    volumes:
      - oracle_data:/opt/oracle/oradata

volumes:
  oracle_data:
